### ISSUE TITLE
Instructions in QuickStart do not work

### ISSUE THREAD

**Issue by troy-phoenix** [brandondocusen/CntxtCS#1]
dotnet tool install --global CntxtCS
**_cntxtcs is not found in NuGet feeds https://www.nuget.org/api/v2/, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"._**

**Comment by brandondocusen** [comment]
instructions updated good catch

**Comment by troy-phoenix** [comment]
☹

 

E:\Projects\Troy\repos\CntxtCS>python CntxtCS.py

Traceback (most recent call last):

  File "E:\Projects\Troy\repos\CntxtCS\CntxtCS.py", line 7, in <module>

    import networkx as nx

ModuleNotFoundError: No module named 'networkx'

**Comment by brandondocusen** [comment]
"pip install networkx" in Powershell or Bash should download and install this missing dependency and fix the error. Be sure to close and reopen your Powershell or Bash window after installing networkx.

You bring up an important issue- automatic dependency checks and installation really should be added to the CntxtCS.py code.
